import env from '@ltv/env'
import fs from 'fs'
import path from 'path'
import { Client } from 'pg'
import { generateSchemaFromDb } from 'shared/utils/graphql'

const schemas = [env('DATABASE_SCHEMA', 'public')]
const nodeEnv = env('NODE_ENV', 'development')
const isProd = () => ['prod', 'production'].indexOf(nodeEnv) != -1
const graphqlDir = path.resolve('./graphql')
if (!fs.existsSync(graphqlDir)) {
  fs.mkdirSync(graphqlDir)
}
const schemaPath = path.resolve(graphqlDir, `schema${isProd() ? '' : '-dev'}.graphql`)
if (fs.existsSync(schemaPath) && isProd()) {
  // Generated in the production
  process.exit()
}

const client = new Client({
  host: env('DATABASE_HOST'),
  database: env('DATABASE_NAME'),
  user: env('DATABASE_USER'),
  password: env('DATABASE_PASS'),
  port: env.int('DATABASE_PORT', 5432),
  ssl: env.bool('DATABASE_SSL', false)
})

const connect = () => client && client.connect()
const disconnect = () => client && client.end()

const getTableQuery = `
SELECT table_schema,table_name, obj_description(oid) as "comment" FROM information_schema.tables
JOIN pg_class ON pg_class.relname = table_name
WHERE "table_schema" IN (${schemas.map((s) => "'" + s + "'").join(',')})
ORDER BY table_schema,table_name;
`

type Table = {
  table_schema: string
  table_name: string
  comment: string
}

async function omitAutoGeneratedTables() {
  const result = await client.query<Table>(getTableQuery)
  const tables = result.rows
  const omitTables: string[] = tables
    .filter((t: Table) => t.table_name.startsWith('_') && !`${t.comment}`.startsWith('@omit'))
    .map((t: Table) => `${t.table_schema}."${t.table_name}"`)

  if (omitTables.length > 0) {
    console.log('omit tables: ', omitTables.join(', '))
    const queries = omitTables.map((t: string) => `comment on table ${t} is E'@omit';`)
    await Promise.all(queries.map((query) => client.query(query)))
  }
}

const run = async () => {
  await connect()
  const generateTo = schemaPath
  await omitAutoGeneratedTables()

  const schema = await generateSchemaFromDb(schemas)
  console.log(`🚀 Generated GraphQL Types from database to '${generateTo}'`)
  fs.writeFileSync(generateTo, schema)
}

run()
  .catch((e) => {
    throw e
  })
  .finally(async () => {
    await disconnect()
  })
