const path = require('path')
const fs = require('fs')

const prismaEnvPath = path.resolve(__dirname, '..', '.env')
const header = '# Generated by tools/prisma-env.js\n# Please do not edit this file manually'

const createPrismaEnv = async () => {
  const env = require('@ltv/env')
  const host = env('DATABASE_HOST')
  const name = env('DATABASE_NAME')
  const user = env('DATABASE_USER')
  const pass = env('DATABASE_PASS')
  const schema = env('DATABASE_SCHEMA', 'public')
  const port = env.int('DATABASE_PORT', 5432)
  const ssl = env.bool('DATABASE_SSL', false)
  let connection = `postgresql://${user}:${pass}@${host}:${port}/${name}?schema=${schema}`
  if (ssl) {
    connection += '&sslmode=require'
  }
  fs.writeFileSync(prismaEnvPath, `${header}\nDATABASE_URL=${connection}`)
  return `DATABASE_URL=${connection}`
}

// createPrismaEnv().then(() => {
//   console.log('Created prisma env at .env')
// })
module.exports = {
  createPrismaEnv,
}
